components:
  schemas:
   product: 
    type: object
    properties:
      title: 
        type: string
        description: Nombre del producto a publicar en la tienda
      category: 
        type: string
        description: Categoria que se quiera definir para el producto
      photo: 
        type: string
        description: URL de la foto a mostrar del producto
      price: 
        type: number
        description: Precio que definimos para la venta del producto
      stock: 
        type: number
        description: Stock que tengamos del producto
    example:
      title: Chupete
      category: Accesorios
      photo: https://i.postimg.cc/pVcL6v4t/package.png
      price: 1500
      stock: 152
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: token
  responses:
    Response200:
      type: object
      properties:
        statuscode:
          type: integer
          format: int64
          description: codigo de estado correspondiente a la solicitud de exito en devolucion de datos
        message:
          type: string
          description: Texto descriptivo con el exito en la operacion
        response:
          type: array
          description: Array de objetos del recurso solicitado
      example:
        statusCode: 200
        message: updated ID
    Response201:
      type: object
      properties:
        statuscode: 
          type: integer
          format: int64
          description: codigo de estado correspondiente a la solicitud de creacion
        message:
          type: string
          description: Texto descriptivo con el exito en la creacion
      example:
        statusCode: 201
        message: 'CREATED ID: 123acdf586dd'
    Paginate:
      type: object
      properties:
        statuscode:
          type: integer
          format: int64
          description: Codigo de estado correspondiente a la solicitud de paginacion de datos
        response:
          type: array
          description: Array de objetos del recurso solicitado paginados
        info:
          type: object
          description: Datos de la paginacion
      example:
        statusCode: 201
        response:
           - title: Chupete
             category: Accesorios
             photo: https://i.postimg.cc/pVcL6v4t/package.png
             price: 1500
             stock: 152
           - title: remera
             category: Indumentaria
             photo: https://i.postimg.cc/pVcL6v4t/package.png
             price: 1500
             stock: 152
           - title: zapatilla
             category: Calzado
             photo: https://i.postimg.cc/pVcL6v4t/package.png
             price: 1500
             stock: 152
        info:
          page: null
          totalPages: null
          limit: null
          prevPage: null
          nextPage: null
    Error400:
      type: object
      properties:
        statuscode:
          type: integer
          format: int64
          description: Codigo de estado correspondiente a la solicitud en errores por parte del cliente
        message:
          type: string
          description: Texto descriptivo con mensaje de error por parte del cliente
      example:
        statusCode: 400
        message: null
    Error401:
      type: object
      properties:
        statuscode:
          type: integer
          format: int64
          description: Codigo de estado correspondiente a la solicitud de error de autenticacion
        message:
          type: string
          description: Texto descriptivo con mensaje de error de atuenticacion
      example:
        statusCode: 401
        message: Bad auth from policies!
    Error403:
      type: object
      properties:
        statuscode:
          type: integer
          format: int64
          description: Codigo de estado correspondiente a la solicitud de error de permisos de autorizacion
        message:
          type: string
          description: Texto descriptivo con mensaje de error de autorizacion
      example:
        statusCode: 403
        message: Forbidden from policies
    Error404:
      type: object
      properties:
        statuscode:
          type: integer
          format: int64
          description: Codigo de estado correspondiente a la solicitud de no encontrado
        message:
          type: string
          description: Texto descriptivo con mensaje de no encontrado de recurso
      example:
        statusCode: 404
        message: Not found docs
    Error500:
      type: object
      properties:
        statuscode:
          type: integer
          format: int64
          description: Codigo de estado correspondiente a la solicitud con respecto a errores internos de servidor
        message:
          type: string
          description: Texto descriptivo con mensaje de error por parte del servidor
      example:
        statusCode: 500
        message: CODER API ERROR
paths: 
  /api/products/:
    post:
      summary: Ruta para registrar un nuevo producto en la base de datos
      tags:
        - product
      security:
        - cookieAuth: []
      requestBody:
        required: true
        description: Datos para registar un producto en la base de datos
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/product'
      responses:
        201:
          description: Creado correctamente
          content:
            aplication/json:
              schema:
                $ref: '#/components/responses/Response201'
        401:
          description: Error de autenticacion de usuario para registar un producto
          content:
            aplication/json:
              schema:
                $ref: '#/components/responses/Error401'
        500:
          description: Error en el servidor
          content:
            aplication/json:
              schema:
                $ref: '#/components/responses/Error500'
  /api/products/{pid}:
    get:
      summary: Ruta para obtener un producto de la base de datos
      tags:
        - product
      parameters:
        - name: pid
          in: path
          required: true
          description: Identificador unico de la mascota a encontrar
          schema:
            $type: string
      responses:
        Response200:
          description: Exito en la letura de una mascota
          content:
            application/json:
              schema:
                $ref: '#/componets/responses/Response200'

      

